# Generated by Django 6.1 on 2026-08-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='apellido_transferencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_transferencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_transferencia',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='venta',
            name='transferencia_verificada',
            field=models.BooleanField(default=False),
        ),
    ]
