# Generated by Django 6.1 on 2026-08-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('VENTA', 'Venta'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('variante_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='inventario.varianteproducto')),
            ],
        ),
    ]
