# Generated by Django 6.1 on 2026-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
