# Generated by Django 6.1 on 2026-08-22 03:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientostock_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplicador_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('descuento_debito', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('descuento_efectivo', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('recargo_finan_ya', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de precios',
                'verbose_name_plural': 'Configuración de precios',
            },
        ),
    ]
